import { getServerSession } from 'next-auth/next';
import { authOptions } from './auth/[...nextauth]';

const MAX_TERM_NAME_LENGTH = 200;
const MAX_AI_RESPONSE_TOKENS = 500;

export default async function handler(req, res) {
  // 1. Check for authentication
  const session = await getServerSession(req, res, authOptions);
  if (!session) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  // 2. Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { termName } = req.body;

  if (!termName || typeof termName !== 'string') {
    return res.status(400).json({ error: 'termName is required and must be a string' });
  }

  if (termName.length < 1 || termName.length > MAX_TERM_NAME_LENGTH) {
    return res.status(400).json({
      error: `termName must be between 1 and ${MAX_TERM_NAME_LENGTH} characters`,
    });
  }

  // Validate API key exists
  if (!process.env.GITHUB_MODELS_API_KEY) {
    console.error('GITHUB_MODELS_API_KEY is not configured');
    return res.status(500).json({ error: 'Server configuration error' });
  }

  try {
    // 3. Call the GitHub Models API on the server
    const response = await fetch('https://models.inference.ai.azure.com/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${process.env.GITHUB_MODELS_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: `You are an expert in FOSS terminology. Generate a concise and accurate glossary entry in YAML format for the given term. The output must be a single YAML object. Include the fields: term, slug, definition, explanation, humorous_description, see_also, and tags. The slug should be a URL-friendly version of the term.`,
          },
          {
            role: 'user',
            content: `Generate a YAML entry for the term: "${termName}"`,
          },
        ],
        max_tokens: MAX_AI_RESPONSE_TOKENS,
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`AI API request failed with status ${response.status}: ${errorBody}`);
    }

    const aiResult = await response.json();

    // Validate response structure
    if (!aiResult.choices || !Array.isArray(aiResult.choices) || aiResult.choices.length === 0) {
      throw new Error('Invalid response structure from AI API');
    }

    const generatedContent = aiResult.choices[0].message?.content;

    if (!generatedContent) {
      throw new Error('No content generated by AI API');
    }

    // 4. Return the generated content to the client
    res.status(200).json({ content: generatedContent });
  } catch (error) {
    console.error('Error calling AI API:', error.message);
    res.status(500).json({ error: 'Failed to generate term from AI API' });
  }
}
