name: On issue assigned to Codex bot

on:
  issues:
    types: [assigned]

permissions:
  issues: write
  pull-requests: write
  contents: read
  actions: read

env:
  ACK_LABEL: in-progress   # label to apply; safe default

jobs:
  acknowledge:
    # NOTE: job-level 'if' cannot use env.* — use vars.* + constants here.
    if: >
      github.event_name == 'issues' &&
      github.event.action == 'assigned' &&
      (
        (vars.CODEX_BOT_LOGIN != '' && github.event.assignee.login == vars.CODEX_BOT_LOGIN) ||
        (vars.CODEX_BOT_LOGIN == '' && github.event.assignee.login == 'codex-bot')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge & label
        uses: actions/github-script@v7
        env:
          # Pass the variable into the step as env so the script can read it
          CODEX_BOT_LOGIN: ${{ vars.CODEX_BOT_LOGIN }}
          ACK_LABEL: ${{ env.ACK_LABEL }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;

            const bot = process.env.CODEX_BOT_LOGIN || 'codex-bot';
            const ackLabel = process.env.ACK_LABEL || 'in-progress';

            // 1) Acknowledge
            await github.rest.issues.createComment({
              owner, repo, issue_number,
              body: `👋 @${bot} subscribed. Starting work.\n\nIf more details are needed, I'll ask here.`
            });

            // 2) Add/create label
            try {
              await github.rest.issues.addLabels({ owner, repo, issue_number, labels: [ackLabel] });
            } catch (e) {
              if (e.status === 404) {
                await github.rest.issues.createLabel({
                  owner, repo, name: ackLabel, color: '0E8A16',
                  description: 'Issue is being handled by the bot'
                }).catch(() => {});
                await github.rest.issues.addLabels({ owner, repo, issue_number, labels: [ackLabel] });
              } else {
                throw e;
              }
            }

            // 3) Job summary
            core.summary
              .addHeading('Codex bot acknowledged')
              .addRaw(`Issue #${issue_number} labeled **${ackLabel}** and acknowledged by **@${bot}**.`)
              .write();
