name: On issue assigned to Codex bot

on:
  issues:
    types: [assigned]

permissions:
  issues: write
  pull-requests: write
  contents: read
  actions: read

env:
  # Single source of truth: set this once in repo Settings → Variables → Actions
  BOT_LOGIN: ${{ vars.CODEX_BOT_LOGIN || 'codex-bot' }}
  ACK_LABEL: in-progress

jobs:
  acknowledge:
    # Only run when the assignee matches BOT_LOGIN
    if: >
      github.event.action == 'assigned' &&
      github.event.assignee.login == env.BOT_LOGIN
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge & label
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const bot = process.env.BOT_LOGIN;
            const ackLabel = process.env.ACK_LABEL || 'in-progress';

            // 1) Comment
            await github.rest.issues.createComment({
              owner, repo, issue_number,
              body: `👋 @${bot} subscribed. Starting work.\n\nIf more details are needed, I'll ask here.`
            });

            // 2) Add/create label
            try {
              await github.rest.issues.addLabels({ owner, repo, issue_number, labels: [ackLabel] });
            } catch (e) {
              if (e.status === 404) {
                await github.rest.issues.createLabel({
                  owner, repo, name: ackLabel, color: '0E8A16',
                  description: 'Issue is being handled by the bot'
                }).catch(() => {});
                await github.rest.issues.addLabels({ owner, repo, issue_number, labels: [ackLabel] });
              } else {
                throw e;
              }
            }

            // 3) Job summary
            core.summary
              .addHeading('Codex bot acknowledged')
              .addRaw(`Issue #${issue_number} labeled **${ackLabel}** and acknowledged by **@${bot}**.`)
              .write();
