name: Build & Deploy Landing Page

on:
  push:
    branches: [main]
    paths:
      - 'terms.yaml'
      - 'scripts/generateLandingPage.js'
      - 'scripts/exportTerms.js'
      - 'docs/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

concurrency:
  group: "docs-updates"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Generate landing page
        run: node scripts/generateLandingPage.js

      - name: Validate landing page is in sync
        run: node scripts/validateLandingPage.js

      - name: Export terms bundle (only if new slugs)
        run: npm run export:new

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
